src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>HC_Leader__c</fullName>
        <label>HC Leader</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMBER</fullName>
                </value>
                <value>
                    <fullName>CAMPBELL</fullName>
                </value>
                <value>
                    <fullName>DON</fullName>
                </value>
                <value>
                    <fullName>MASTER</fullName>
                </value>
                <value>
                    <fullName>OWEN</fullName>
                </value>
                <value>
                    <fullName>RICHARD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HC_Leader__c</fullName>
        <description>The HealthCert Education Adviser who is the Leader for this opportunity and receives recognition for the sale.</description>
        <inlineHelpText>The HealthCert Education Adviser who is the Leader for this opportunity and receives recognition for the sale.</inlineHelpText>
        <label>HC Leader</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMBER</fullName>
                </value>
                <value>
                    <fullName>CAMPBELL</fullName>
                </value>
                <value>
                    <fullName>DON</fullName>
                </value>
                <value>
                    <fullName>MASTER</fullName>
                    <default>true</default>
                    <label>MASTER</label>
                </value>
                <value>
                    <fullName>OWEN</fullName>
                </value>
                <value>
                    <fullName>RICHARD</fullName>
                </value>
                <value>
                    <fullName>LUCY</fullName>
                </value>
                <value>
                    <fullName>LORETTA</fullName>
                </value>
                <value>
                    <fullName>ADELINA</fullName>
                    <isActive>false</isActive>
                    <label>ADELINA</label>
                </value>
                <value>
                    <fullName>ADMIN</fullName>
                    <isActive>false</isActive>
                    <label>ADMIN</label>
                </value>
                <value>
                    <fullName>AURELIO</fullName>
                    <isActive>false</isActive>
                    <label>AURELIO</label>
                </value>
                <value>
                    <fullName>Automated Process</fullName>
                    <isActive>false</isActive>
                    <label>Automated Process</label>
                </value>
                <value>
                    <fullName>BOYD</fullName>
                    <isActive>false</isActive>
                    <label>BOYD</label>
                </value>
                <value>
                    <fullName>CHRISW</fullName>
                    <isActive>false</isActive>
                    <label>CHRISW</label>
                </value>
                <value>
                    <fullName>Campbell Elton</fullName>
                    <isActive>false</isActive>
                    <label>Campbell Elton</label>
                </value>
                <value>
                    <fullName>Chatter Expert</fullName>
                    <isActive>false</isActive>
                    <label>Chatter Expert</label>
                </value>
                <value>
                    <fullName>Chris Watt</fullName>
                    <isActive>false</isActive>
                    <label>Chris Watt</label>
                </value>
                <value>
                    <fullName>DARREN</fullName>
                    <isActive>false</isActive>
                    <label>DARREN</label>
                </value>
                <value>
                    <fullName>DM User</fullName>
                    <isActive>false</isActive>
                    <label>DM User</label>
                </value>
                <value>
                    <fullName>EMMA</fullName>
                    <isActive>false</isActive>
                    <label>EMMA</label>
                </value>
                <value>
                    <fullName>Emma Kipping</fullName>
                    <isActive>false</isActive>
                    <label>Emma Kipping</label>
                </value>
                <value>
                    <fullName>Hamish Elton</fullName>
                    <isActive>false</isActive>
                    <label>Hamish Elton</label>
                </value>
                <value>
                    <fullName>JACKIE</fullName>
                    <isActive>false</isActive>
                    <label>JACKIE</label>
                </value>
                <value>
                    <fullName>JAN</fullName>
                    <isActive>false</isActive>
                    <label>JAN</label>
                </value>
                <value>
                    <fullName>JEREMY</fullName>
                    <isActive>false</isActive>
                    <label>JEREMY</label>
                </value>
                <value>
                    <fullName>Jackie Lyn Delfin-Anapio</fullName>
                    <isActive>false</isActive>
                    <label>Jackie Lyn Delfin-Anapio</label>
                </value>
                <value>
                    <fullName>Kingsford Todd</fullName>
                    <isActive>false</isActive>
                    <label>Kingsford Todd</label>
                </value>
                <value>
                    <fullName>LEISA</fullName>
                    <isActive>false</isActive>
                    <label>LEISA</label>
                </value>
                <value>
                    <fullName>Leisa Feeze-Collins</fullName>
                    <isActive>false</isActive>
                    <label>Leisa Feeze-Collins</label>
                </value>
                <value>
                    <fullName>Loretta Blackborough</fullName>
                    <isActive>false</isActive>
                    <label>Loretta Blackborough</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityEmail__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>OpportunityEmail</label>
</CustomObject>

src/classes/UpdateOpportunity_Helper.cls
public class UpdateOpportunity_Helper {
    
    public static void updateOpportunityField(map<id,opportunity> newoppmap,map<id,opportunity> oldoppmap, list<opportunity> opportunitylist) {
        try {
            system.debug('updateOpportunityField>>>>>>>>>>>>>>');
            
            string allname = '';
            
            List<Messaging.SingleEmailMessage > singleEmailMessageList=new List<Messaging.SingleEmailMessage>();
            OpportunityEmail__c mc = OpportunityEmail__c.getOrgDefaults();
            
            set <id>  accid = new set <id>();
            
            for(opportunity objopp : opportunitylist){
                
                if(objopp.AccountId!=null){
                    
                    accid.add(objopp.AccountId);
                    
                }
                
            }
            
            system.debug('OpportunityEmail__c>>>>>>>>>>>>'+mc.Email__c);
            
            map<id,string> accmap = new map <id,string>();
            
            list <opportunity> opplist = [select accountid,opportunity.account.name from opportunity where accountid in : accid];
            
            for (opportunity oppObj : opplist){
                
                if(oppObj.AccountId!=null){
                    
                    accmap.put(oppObj.AccountId,oppObj.account.name);
                }
                
            }
            
            for (opportunity objopp : opportunitylist) {
                
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                
                if (oldoppmap.containsKey(objopp.Id) &&
                    newoppmap.get(objopp.Id).HC_Leader__c != oldoppmap.get(objopp.Id).HC_Leader__c) {
                        
                        allname = oldoppmap.get(objopp.Id).HC_Leader__c +'\n' +newoppmap.get(objopp.Id).HC_Leader__c +'\n'+ UserInfo.getName() +'\n'+ accmap.get(objopp.AccountId) +'\n'+ URL.getSalesforceBaseUrl().toExternalForm() +'/' + objopp.id;
                        
                        system.debug('allname>>>>>>>>>>>>'+allname);
                        
                        string htmlbody = 'Changed from: ' + oldoppmap.get(objopp.Id).HC_Leader__c + '<br/><br/>'+ 'Change to: '+ newoppmap.get(objopp.Id).HC_Leader__c+'<br/><br/>' + 'Changed by: ' +  UserInfo.getName()+'<br/><br/>' + 'Account Name: ' +  accmap.get(objopp.AccountId)+'<br/><br/>' + 'Opportunity Record - URL: ' +  URL.getSalesforceBaseUrl().toExternalForm() +'/' + objopp.id;
                        email.setHtmlBody(htmlBody);
                        email.setSubject('HC Leader Change Update');
                        email.setToAddresses(new List<String>{mc.Email__c});
                        singleEmailMessageList.add(email);
                    }
                
            }
            Messaging.SendEmailResult [] r = Messaging.sendEmail(singleEmailMessageList);
            System.debug('Result----'+r);
            
            
        }
                
        catch (Exception e) {
            
            system.debug('Error>>>>>>>>>>>' + e.getMessage() + 'At line number>>>>>>>>>>' + e.getLineNumber());
        }
    }
}