src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email_Address_2__c</fullName>
        <description>SK</description>
        <label>Email Address 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>HC_Leader__c</fullName>
        <label>HC Leader</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMBER</fullName>
                </value>
                <value>
                    <fullName>CAMPBELL</fullName>
                </value>
                <value>
                    <fullName>DON</fullName>
                </value>
                <value>
                    <fullName>MASTER</fullName>
                </value>
                <value>
                    <fullName>OWEN</fullName>
                </value>
                <value>
                    <fullName>RICHARD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Created_by_Api__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox will be true if opportunity is created by api.</description>
        <label>Created by Api</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HC_Leader__c</fullName>
        <description>The HealthCert Education Adviser who is the Leader for this opportunity and receives recognition for the sale.</description>
        <inlineHelpText>The HealthCert Education Adviser who is the Leader for this opportunity and receives recognition for the sale.</inlineHelpText>
        <label>HC Leader</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AMBER</fullName>
                </value>
                <value>
                    <fullName>CAMPBELL</fullName>
                </value>
                <value>
                    <fullName>DON</fullName>
                </value>
                <value>
                    <fullName>MASTER</fullName>
                    <default>true</default>
                    <label>MASTER</label>
                </value>
                <value>
                    <fullName>OWEN</fullName>
                </value>
                <value>
                    <fullName>RICHARD</fullName>
                </value>
                <value>
                    <fullName>LUCY</fullName>
                </value>
                <value>
                    <fullName>LORETTA</fullName>
                </value>
                <value>
                    <fullName>ADELINA</fullName>
                    <isActive>false</isActive>
                    <label>ADELINA</label>
                </value>
                <value>
                    <fullName>ADMIN</fullName>
                    <isActive>false</isActive>
                    <label>ADMIN</label>
                </value>
                <value>
                    <fullName>AURELIO</fullName>
                    <isActive>false</isActive>
                    <label>AURELIO</label>
                </value>
                <value>
                    <fullName>Automated Process</fullName>
                    <isActive>false</isActive>
                    <label>Automated Process</label>
                </value>
                <value>
                    <fullName>BOYD</fullName>
                    <isActive>false</isActive>
                    <label>BOYD</label>
                </value>
                <value>
                    <fullName>CHRISW</fullName>
                    <isActive>false</isActive>
                    <label>CHRISW</label>
                </value>
                <value>
                    <fullName>Campbell Elton</fullName>
                    <isActive>false</isActive>
                    <label>Campbell Elton</label>
                </value>
                <value>
                    <fullName>Chatter Expert</fullName>
                    <isActive>false</isActive>
                    <label>Chatter Expert</label>
                </value>
                <value>
                    <fullName>Chris Watt</fullName>
                    <isActive>false</isActive>
                    <label>Chris Watt</label>
                </value>
                <value>
                    <fullName>DARREN</fullName>
                    <isActive>false</isActive>
                    <label>DARREN</label>
                </value>
                <value>
                    <fullName>DM User</fullName>
                    <isActive>false</isActive>
                    <label>DM User</label>
                </value>
                <value>
                    <fullName>EMMA</fullName>
                    <isActive>false</isActive>
                    <label>EMMA</label>
                </value>
                <value>
                    <fullName>Emma Kipping</fullName>
                    <isActive>false</isActive>
                    <label>Emma Kipping</label>
                </value>
                <value>
                    <fullName>Hamish Elton</fullName>
                    <isActive>false</isActive>
                    <label>Hamish Elton</label>
                </value>
                <value>
                    <fullName>JACKIE</fullName>
                    <isActive>false</isActive>
                    <label>JACKIE</label>
                </value>
                <value>
                    <fullName>JAN</fullName>
                    <isActive>false</isActive>
                    <label>JAN</label>
                </value>
                <value>
                    <fullName>JEREMY</fullName>
                    <isActive>false</isActive>
                    <label>JEREMY</label>
                </value>
                <value>
                    <fullName>Jackie Lyn Delfin-Anapio</fullName>
                    <isActive>false</isActive>
                    <label>Jackie Lyn Delfin-Anapio</label>
                </value>
                <value>
                    <fullName>Kingsford Todd</fullName>
                    <isActive>false</isActive>
                    <label>Kingsford Todd</label>
                </value>
                <value>
                    <fullName>LEISA</fullName>
                    <isActive>false</isActive>
                    <label>LEISA</label>
                </value>
                <value>
                    <fullName>Leisa Feeze-Collins</fullName>
                    <isActive>false</isActive>
                    <label>Leisa Feeze-Collins</label>
                </value>
                <value>
                    <fullName>Loretta Blackborough</fullName>
                    <isActive>false</isActive>
                    <label>Loretta Blackborough</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_trigger_switch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IsCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCheck</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity trigger switch</label>
</CustomObject>

src/objects/OpportunityEmail__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>OpportunityEmail</label>
</CustomObject>

src/classes/UpdateOpportunity_HelperTest.cls
@isTest
public class UpdateOpportunity_HelperTest {
    
    @isTest
    public static void updateOpportunity(){
        try {
                       
            Opportunity_trigger_switch__c objcusOpp = new Opportunity_trigger_switch__c();
            objcusOpp.IsCheck__c = true;
            objcusOpp.Name = 'OpportunityTrigger';
            insert objcusOpp;
            
            OpportunityEmail__c objoppemail = new OpportunityEmail__c();
            objoppemail.Name = 'testemail';
            objoppemail.Email__c = 'test@gmail.com';
            insert objoppemail;
                
            Account objAcc = new Account();
            objAcc.name = 'TestAcc';
            objAcc.Email_Address_2__c = 'mohit@gmail.com';
            objAcc.Phone = '78798798';
            insert objAcc;
            
            opportunity objopp = new opportunity();
            objopp.name = 'testOpp';
            objopp.StageName = 'Completed';
            objopp.Created_by_Api__c = false;
            objopp.CloseDate = date.today();
            objopp.HC_Leader__c = 'BOYD';
            objopp.Amount = 43;
            objopp.AccountId = objAcc.id;
            insert objopp;
          
            Test.startTest();                  
            objopp.HC_Leader__c = 'LUCY';
            update objopp;
            Test.startTest();
            
        }
        catch(Exception Ex){
            
            System.debug('Error>>>>>>>>>>>'+Ex.getMessage()+'At line number'+Ex.getLineNumber());
        }
    }
}