src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Courses_Interested_In__c</fullName>
        <label>Courses Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015-ADERM-Online</fullName>
                </value>
                <value>
                    <fullName>2015-ADL-SCMED</fullName>
                </value>
                <value>
                    <fullName>2015-ADL-SCSUG</fullName>
                </value>
                <value>
                    <fullName>2015-BNE-SCMAS</fullName>
                </value>
                <value>
                    <fullName>2015-GDCERT</fullName>
                </value>
                <value>
                    <fullName>2015-MEL-PCOP</fullName>
                </value>
                <value>
                    <fullName>2015-OOL-ADSG</fullName>
                </value>
                <value>
                    <fullName>2015-SCMAS</fullName>
                </value>
                <value>
                    <fullName>2015-SCMED-Online</fullName>
                </value>
                <value>
                    <fullName>2015-SYD-ADSG</fullName>
                </value>
                <value>
                    <fullName>2015-SYD-PCOP</fullName>
                </value>
                <value>
                    <fullName>2015-USA</fullName>
                </value>
                <value>
                    <fullName>ACDER</fullName>
                </value>
                <value>
                    <fullName>ADERM</fullName>
                </value>
                <value>
                    <fullName>ADSG</fullName>
                </value>
                <value>
                    <fullName>ASTH1</fullName>
                </value>
                <value>
                    <fullName>ASTH2</fullName>
                </value>
                <value>
                    <fullName>ASTH3</fullName>
                </value>
                <value>
                    <fullName>Clinical Attachment</fullName>
                </value>
                <value>
                    <fullName>DIPDER</fullName>
                </value>
                <value>
                    <fullName>GDERM</fullName>
                </value>
                <value>
                    <fullName>GPCU</fullName>
                </value>
                <value>
                    <fullName>MBUS</fullName>
                </value>
                <value>
                    <fullName>PCDER</fullName>
                </value>
                <value>
                    <fullName>PCOP</fullName>
                </value>
                <value>
                    <fullName>SCCMCLASS-2016</fullName>
                </value>
                <value>
                    <fullName>SCCONF 2015</fullName>
                </value>
                <value>
                    <fullName>SCCONF-2016</fullName>
                </value>
                <value>
                    <fullName>SCMED</fullName>
                </value>
                <value>
                    <fullName>SCSUG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MoodlePass__c</fullName>
        <label>MoodlePass</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MoodleUser__c</fullName>
        <label>MoodleUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Type__c</fullName>
        <label>Phone Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
                <value>
                    <fullName>Home</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Profession__c</fullName>
        <label>Profession</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Doctor</fullName>
                </value>
                <value>
                    <fullName>Dermatologist</fullName>
                </value>
                <value>
                    <fullName>General Practitioner</fullName>
                </value>
                <value>
                    <fullName>Family Physician</fullName>
                </value>
                <value>
                    <fullName>GP Registrar</fullName>
                </value>
                <value>
                    <fullName>Doctor in Training</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Registration_Date__c</fullName>
        <label>Registration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sync_With_HubSpot__c</fullName>
        <label>Sync With HubSpot</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WEB_ID__c</fullName>
        <label>WEB ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Conf_Workshop_1__c</fullName>
        <label>Conf Workshop 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CPD Points Uploaded</fullName>
                </value>
                <value>
                    <fullName>Did not attend</fullName>
                </value>
                <value>
                    <fullName>WaitList</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Courses_Interested_In__c</fullName>
        <label>Courses Interested In</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACDER</fullName>
                </value>
                <value>
                    <fullName>ADERM</fullName>
                </value>
                <value>
                    <fullName>ADERM Online</fullName>
                </value>
                <value>
                    <fullName>ADSGHN</fullName>
                </value>
                <value>
                    <fullName>ADSGNL</fullName>
                </value>
                <value>
                    <fullName>ASTH1</fullName>
                </value>
                <value>
                    <fullName>CLATT</fullName>
                </value>
                <value>
                    <fullName>DIPDER</fullName>
                </value>
                <value>
                    <fullName>GDCERT</fullName>
                </value>
                <value>
                    <fullName>GDERM</fullName>
                </value>
                <value>
                    <fullName>GPUP</fullName>
                </value>
                <value>
                    <fullName>MEDBUS</fullName>
                </value>
                <value>
                    <fullName>PCDER</fullName>
                </value>
                <value>
                    <fullName>PCOP</fullName>
                </value>
                <value>
                    <fullName>SCCONF-2016</fullName>
                </value>
                <value>
                    <fullName>SCMAS</fullName>
                </value>
                <value>
                    <fullName>SCMED</fullName>
                </value>
                <value>
                    <fullName>SCMED Online</fullName>
                </value>
                <value>
                    <fullName>SCSUG</fullName>
                </value>
                <value>
                    <fullName>SCTIC</fullName>
                </value>
                <value>
                    <fullName>SKBUS</fullName>
                </value>
                <value>
                    <fullName>SKINBUS Online</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Created_by_Api__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox will be true if opportunity is created by api.</description>
        <label>Created by Api</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OppStatus__c</fullName>
        <label>OppStatus</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EnrolmentCompleted</fullName>
                </value>
                <value>
                    <fullName>CreditCardSelected</fullName>
                    <label>Credit Card</label>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>DirectDeposit</fullName>
                </value>
                <value>
                    <fullName>Free of Charge</fullName>
                </value>
                <value>
                    <fullName>Waitlist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Registration_Date__c</fullName>
        <label>Registration Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source_of_Enquiry_or_Registration__c</fullName>
        <label>Source of Enquiry or Registration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACRRM Newsletter</fullName>
                </value>
                <value>
                    <fullName>Allied Medical</fullName>
                </value>
                <value>
                    <fullName>ARL</fullName>
                </value>
                <value>
                    <fullName>Australian Doctor Magazine</fullName>
                </value>
                <value>
                    <fullName>Australian Family Physician</fullName>
                </value>
                <value>
                    <fullName>Colleague Referral</fullName>
                </value>
                <value>
                    <fullName>College or Association</fullName>
                </value>
                <value>
                    <fullName>Direct Email</fullName>
                </value>
                <value>
                    <fullName>Direct Mail</fullName>
                </value>
                <value>
                    <fullName>Division Newsletter</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Fax News Release</fullName>
                </value>
                <value>
                    <fullName>GP Conference</fullName>
                </value>
                <value>
                    <fullName>GP16 Conference</fullName>
                </value>
                <value>
                    <fullName>HelloBar</fullName>
                </value>
                <value>
                    <fullName>IMC Conference</fullName>
                </value>
                <value>
                    <fullName>Internet Research</fullName>
                </value>
                <value>
                    <fullName>Internet Search</fullName>
                </value>
                <value>
                    <fullName>Last Years Courses</fullName>
                </value>
                <value>
                    <fullName>Masters Student</fullName>
                </value>
                <value>
                    <fullName>Medical Observer</fullName>
                </value>
                <value>
                    <fullName>Medical Republic</fullName>
                </value>
                <value>
                    <fullName>Molescan</fullName>
                </value>
                <value>
                    <fullName>New Zealand Doctor</fullName>
                </value>
                <value>
                    <fullName>Online Ads</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Past Conference</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Previous Course Attendance</fullName>
                </value>
                <value>
                    <fullName>Print Brochure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WorkbookFormat__c</fullName>
        <label>WorkbookFormat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/commonClassTracker.cls
/*
    This is the common class in which we insert all object record.
    =================================================================================
    Created By                          Date                            Version
    =================================================================================
    Lav Singh                        24-10-2017                           1.0

*/
public class commonClassTracker
{
    public static account accountRecord(string objFirstName,string objLastName,string objPhone,string objPersonEmail,string ObjSalutation,string objphoneType,string objWebId,Date objRegistrationDate,string objMoodleUser,string objMoodlePass,string objProfession,string objCategory,string syncWithHubspot)
    {
        Account objAccount = new Account();
        objAccount.FirstName =objFirstName; 
        objAccount.LastName =objLastName;  
        objAccount.Phone =objPhone;  
        objAccount.PersonEmail =objPersonEmail;  
        objAccount.Salutation =ObjSalutation;  
        objAccount.Phone_Type__c =objphoneType;  
        objAccount.WEB_ID__c =objWebId;  
        objAccount.Registration_Date__c = objRegistrationDate;  
        objAccount.MoodleUser__c =objMoodleUser;  
        objAccount.MoodlePass__c =objMoodlePass;  
        objAccount.Profession__c =objProfession;
        objAccount.Sync_With_HubSpot__c =syncWithHubspot; 
        return objAccount;
    }
    public static opportunity opportunityRecord(string objName,Boolean objcreatedbyapi,string objStageName,Date closeDate,Integer ObjRevenue,string objOppStatus,string objCoursesInterested,string objconfWorkshop,string objWorkbookFormat,string objSourceofinquery,string objcoursecode,string objpaymentMethod,string objpaymentStatus,string objLeadsourse,string objPartnerMarketing,string objOpportunityUTM)
    {
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.Name =objName;
        objOpportunity.Created_by_Api__c =objcreatedbyapi;
        objOpportunity.StageName =objStageName;
        objOpportunity.CloseDate =closeDate;
        objOpportunity.Revenue__c =ObjRevenue;
        objOpportunity.OppStatus__c =objOppStatus;
        objOpportunity.Courses_Interested_In__c =objCoursesInterested;
        objOpportunity.Conf_Workshop_1__c =objconfWorkshop;
        objOpportunity.WorkbookFormat__c =objWorkbookFormat;
        objOpportunity.Source_of_Enquiry_or_Registration__c =objSourceofinquery;
        objOpportunity.Course_Code__c =objcoursecode;
        objOpportunity.Payment_Method__c =objpaymentMethod;
        objOpportunity.Payment_Status__c =objpaymentStatus;
        objOpportunity.LeadSource =objLeadsourse;
        objOpportunity.PartnerMarketing__c =objPartnerMarketing;
        objOpportunity.Opportunity_UTM__c =objOpportunityUTM;
        return objOpportunity;
    }
    public static Json_Key_Object_Field_mapping__c objJsonKeyObjectfieldMappingRecord(string objName,string objDataType,string objObjectName,string objSFFieldApi)
    {
        Json_Key_Object_Field_mapping__c objJsonmapping = new Json_Key_Object_Field_mapping__c();
        objJsonmapping.Name = objName;
        objJsonmapping.Data_Type__c =objDataType;
        objJsonmapping.Object_Name__c =objObjectName;
        objJsonmapping.SF_Field_Api__c =objSFFieldApi;
        return objJsonmapping;
    }
    
    
   public static Product2 productRecord(string objProductName,String objCourseID,String objProductCode,Decimal objFullPrice,String objDescription,String objFamily,Boolean objIsActive)
    {
        Product2 objProduct = new Product2();
        objProduct.Name =objProductName;
        objProduct.Course_ID__c=objCourseID;
         objProduct.Description=objDescription;
            objProduct.Family=objFamily;
            objProduct.IsActive=objIsActive;
            objProduct.ProductCode=objProductCode;
            objProduct.Full_Price__c=objFullPrice;
            return objProduct;
    }
    
    public static PriceBookEntry addProductToPriceBook(Product2 objProduct)
    {
        
 Id pricebookId = Test.getStandardPricebookId();
        PriceBookEntry pbe=new PriceBookEntry();

        pbe.Product2Id=objProduct.id;
            pbe.Pricebook2Id= pricebookId;
            pbe.UnitPrice=objProduct.Full_Price__c;
            pbe.Early_Bird__c=objProduct.Early_Bird__c;
            pbe.Early_Price__c=objProduct.Early_Price__c;
            pbe.IsActive=true;
        
        return pbe;
    }
    
}