src/objects/Notes__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32700</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
                <value>
                    <fullName>Free of Charge</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>AMEX</fullName>
                    <isActive>false</isActive>
                    <label>AMEX</label>
                </value>
                <value>
                    <fullName>American Express</fullName>
                    <isActive>false</isActive>
                    <label>American Express</label>
                </value>
                <value>
                    <fullName>Corporate Account</fullName>
                    <isActive>false</isActive>
                    <label>Corporate Account</label>
                </value>
                <value>
                    <fullName>Paid in Full</fullName>
                    <isActive>false</isActive>
                    <label>Paid in Full</label>
                </value>
                <value>
                    <fullName>Payment via Credit Card</fullName>
                    <isActive>false</isActive>
                    <label>Payment via Credit Card</label>
                </value>
                <value>
                    <fullName>Payment via Direct Deposit</fullName>
                    <isActive>false</isActive>
                    <label>Payment via Direct Deposit</label>
                </value>
                <value>
                    <fullName>UQ Masters Account</fullName>
                    <isActive>false</isActive>
                    <label>UQ Masters Account</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_trigger_switch__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IsCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCheck</label>
        <type>Checkbox</type>
    </fields>
    <label>Opportunity trigger switch</label>
</CustomObject>

src/classes/Opportunity_Notes_RelatedList_Class_Test.cls
@isTest  
public class Opportunity_Notes_RelatedList_Class_Test {
    static testMethod void validateOpportunity_Notes_RelatedList_Class() {

        Opportunity_trigger_switch__c objTrigger = new Opportunity_trigger_switch__c();
        objTrigger.Name ='OpportunityTrigger';
        objTrigger.IsCheck__c =True;
        insert objTrigger;
        
     /*   Opportunity opp = New Opportunity();
        opp.Name = 'test Opportunity';
        opp.StageName = 'Completed';
        opp.Probability = 5;
        insert opp; */
        
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
        Account objAccount = commonClassTracker.accountRecord('Todd','Kingsford','868266776','regotestsf@vexill.com','Mr.','Mobile','12355',Date.Today(),'Moddle User','Moodle Pass','Doctor','Doctor','Yes');
        objAccount.RecordTypeId = accRecordTypeId ;
        insert objAccount;
        
        Opportunity objOpportunity = commonClassTracker.opportunityRecord('QA',false,'Paid',Date.Today(),10000,'EnrolmentCompleted','ACDER','CPD Points Uploaded','test','ACRRM Newsletter','ACDER','American Express','Free of Charge','Facebook','Yes','Test UTM');
        objOpportunity.AccountId = objAccount.id;
        objOpportunity.Payment_Method__c = 'Credit Card';
        insert objOpportunity;

        Notes__c no = New Notes__c();
        no.opportunity__c = objOpportunity.Id;
        no.Body__c = 'This should be a big paragraph. This should be a big paragraph. This should be a big paragraph. This should be a big paragraph';
        insert no;
        
     /*   Opportunity opp1 = New Opportunity();
        opp1.Name = 'test Opportunity';
        opp1.StageName = 'Completed';
        opp1.Probability = 5;
        insert opp1; */
        
        Notes__c no1 = New Notes__c();
        no1.opportunity__c = objOpportunity.Id;
        no1.Body__c = 'This should be a big paragraph. This should be a big paragraph. This should be a big paragraph. This should be a big paragraph';
        insert no1;
        
        Opportunity objOpportunity1 = commonClassTracker.opportunityRecord('QA',false,'Paid',Date.Today(),10000,'EnrolmentCompleted','ACDER','CPD Points Uploaded','test','ACRRM Newsletter','ACDER','American Express','Free of Charge','Facebook','Yes','Test UTM');
        objOpportunity1.AccountId = objAccount.id;
        objOpportunity1.Payment_Method__c = 'Credit Card';
        try
        {
            insert objOpportunity1;
        }
        catch(exception ex)
        {
            system.debug('ex==========='+ex);
        }
        
        
        //delete no;
        
        Apexpages.StandardController sc = new Apexpages.StandardController(objOpportunity);

        Opportunity_Notes_RelatedList_Class nrlc = New Opportunity_Notes_RelatedList_Class(sc); 
        nrlc.newnotes();
        nrlc.editnotes();
        //nrlc.deletenotes();
        
        Apexpages.StandardController sc1 = new Apexpages.StandardController(objOpportunity);

        Opportunity_Notes_RelatedList_Class nrlc1 = New Opportunity_Notes_RelatedList_Class(sc1); 
        
        PageReference pageRef = Page.Opportunity_Notes_RelatedList;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('notes__cId',No1.id);
        nrlc1.deletenotes(); 
    }
}