src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Course_ID__c</fullName>
        <label>Course ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Full_Price__c</fullName>
        <label>Full Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProducTriggerHandlerTracker.cls
@isTest(seealldata=true)
public class ProducTriggerHandlerTracker {

    
    static testMethod void testProductUpdation() 
    {
 Product2 objProdforUAT1= new Product2(Name='UAT Test Product',Family = 'None',isActive=true,Course_ID__c ='UAT',Full_Price__c =20);
        insert objProdforUAT1;
           Pricebook2 spb=[select id, name from pricebook2 where Name='Standard Price Book'];

        objProdforUAT1.Full_Price__c=30;
        update objProdforUAT1;
    }
}